### ISSUE TITLE
Please clarify the license of the library

### ISSUE THREAD

**Issue by t-paul** [OskarLinde/scad-utils#5]
The library has lots of nice code which is generally useful, but without a clear license, it's basically not possible to distribute the code along with OpenSCAD or as separate package in Linux distributions. I hope you would like to see it included / distributed, so please add a license to make it possible.

**Comment by OskarLinde** [comment]
Thanks, added MIT License file (484d39bc2fd19cf6903c8e92e01af40a77276e66).

**Comment by t-paul** [comment]
Awesome, thanks.
